# Generated by Django 4.2.3 on 2023-07-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisiments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisiment',
            table='advertisiments',
        ),
    ]
