# Generated by Django 4.2.3 on 2023-08-11 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_advertisiments', '0002_alter_advertisiment_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisiment',
            options={'verbose_name': 'App_Advertisiments', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddField(
            model_name='advertisiment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
            preserve_default=False,
        ),
    ]
