# Generated by Django 4.2.3 on 2023-08-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisiments', '0003_alter_advertisiment_options_advertisiment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisiment',
            name='image',
            field=models.ImageField(default='', upload_to='advertisiments/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
